import type { IQuizRepository } from '@domain/repositories/quiz-repository';
import type { IAuditLogRepository } from '@domain/repositories/audit-log-repository';
import type { CreateQuizDTO } from '@application/dtos/quiz-admin.dto';
import { Quiz, QuizSettings } from '@domain/entities/quiz';
import { AuditLog, AuditEventType } from '@domain/entities/audit-log';
import { generateJoinCode } from '@lib/join-code';
import { randomUUID } from 'crypto';

export class CreateQuizUseCase {
  constructor(
    private readonly quizRepository: IQuizRepository,
    private readonly auditLogRepository?: IAuditLogRepository
  ) {}

  async execute(data: CreateQuizDTO): Promise<string> {
    const settings: QuizSettings = {
      timePerQuestion: data.timePerQuestion,
      allowSkipping: data.allowSkipping,
    };

    const joinCode = generateJoinCode();
    const quiz = new Quiz(
      '', // ID will be generated by repository
      data.title,
      [], // No questions initially
      settings,
      { joinCode }
    );

    const savedQuiz = await this.quizRepository.create(quiz);

    if (this.auditLogRepository) {
      void this.auditLogRepository
        .save(
          new AuditLog(randomUUID(), AuditEventType.QuizCreated, {
            quizId: savedQuiz.id,
            metadata: { title: data.title },
          })
        )
        .catch((error) =>
          console.error('[AuditLog] create-quiz save failed:', error)
        );
    }

    return savedQuiz.id;
  }
}
