import type { IQuizRepository } from '@domain/repositories/quiz-repository';
import type { CreateQuizDTO } from '@application/dtos/quiz-admin.dto';
import { Quiz, QuizSettings } from '@domain/entities/quiz';
import { generateJoinCode } from '@lib/join-code';

export class CreateQuizUseCase {
  constructor(private readonly quizRepository: IQuizRepository) {}

  async execute(data: CreateQuizDTO): Promise<string> {
    const settings: QuizSettings = {
      timePerQuestion: data.timePerQuestion,
      allowSkipping: data.allowSkipping,
    };

    const joinCode = generateJoinCode();
    const quiz = new Quiz(
      '', // ID will be generated by repository
      data.title,
      [], // No questions initially
      settings,
      { joinCode }
    );

    const savedQuiz = await this.quizRepository.create(quiz);
    return savedQuiz.id;
  }
}
